### ISSUE TITLE
Customise option

### ISSUE THREAD

**Issue by kaazima** [aravindvnair99/Spot-the-Hole#17]
**Description of the bug:**
Customise option is not working properly.

**Steps to reproduce the behaviour:**
1. Go to 'https://spot-the-hole.web.app'
2. Click on 'customise'
3. See error

**Expected behaviour:**
It is supposed to respond as I click on any of the customise options.

**Screenshot:**
![image](https://user-images.githubusercontent.com/59416370/85205613-103b0580-b33a-11ea-83a3-1087438e5900.png)

**Desktop:**
 - OS: Windows
 - Browser: Google Chrome
 - Version: 83.0.4103.106

**Comment by aravindvnair99** [comment]
@kaazima can you confirm if the bug still exists?

**Comment by kaazima** [comment]
Yeah, customise option is working properly now. It looks perfect :)
