### ISSUE TITLE
Gap in between footer and footer menu

### ISSUE THREAD

**Issue by Priya378** [aravindvnair99/Spot-the-Hole#18]
**Description of the bug:**
Footer is not sticking to footer menu which is leading to a gap in between them. This can be observed when the footer type is set to 'minimal footer' on the pages 'Capture' and 'Notifications' and even on the page 'Dashboard' when no potholes have been reported by the user. This gap is negligible on phone screens.

**To Reproduce the behaviour:**

1. Go to 'https://spot-the-hole.web.app'
2. Click on 'Capture' or on 'Notifications'
3. Set 'Page Footer Type' to 'Minimal Footer' in the options to customise.
4. Observe the gap in between footer and footer menu.

**Expected behaviour:**
Footer is supposed to stick to footer menu i.e, gap should not be visible.

**Screenshot:**

![capture](https://user-images.githubusercontent.com/59410993/85224739-0ec91600-b3ea-11ea-9c45-acca44bacecf.PNG)

**Desktop:**
 - OS: Windows
 - Browser: Google Chrome
 - Version: 83.0.4103.106

**Comment by aravindvnair99** [comment]
@Priya378 can you confirm if the bug still exists?

**Comment by Priya378** [comment]
It is fixed on the page 'Capture', but it is still the same on the page 'Notifications'.
[cid:d5bf1931-d0f2-4ab8-bcac-2720e0e1d54a]
________________________________
